CREATE DATABASE StudentLibraryManagement;

USE StudentLibraryManagement;

CREATE TABLE STUDENT
(
ROLL VARCHAR(4) PRIMARY KEY,
NAME VARCHAR(50)
);

CREATE TABLE librarian(
LIB_ID VARCHAR(4) PRIMARY KEY,
LIB_NAME VARCHAR(50)
);

DROP TABLE LIBRARIAN;

CREATE TABLE BOOK
(
BOOK_ID VARCHAR(4) PRIMARY KEY,
BOOK_NAME VARCHAR(50),
BOOK_GENRE VARCHAR(50)
);

CREATE TABLE BORROW
(
WHO_BORROWED_ROLL VARCHAR(4),
WHICH_BOOK_ID VARCHAR(4),
NAME VARCHAR(50),
BORROW_DATE DATE,
RETURN_DATE DATE,

constraint FK1 FOREIGN KEY (WHO_BORROWED_ROLL) REFERENCES STUDENT(ROLL),
constraint FK2 FOREIGN KEY (WHICH_BOOK_ID) REFERENCES BOOK(BOOK_ID),
PRIMARY KEY (WHO_BORROWED_ROLL, WHICH_BOOK_ID)
);

CREATE TABLE PERMISSION
(
	WHICH_BOOK_ID VARCHAR(4),
    WHO_PERMITTED_LIB_ID VARCHAR(4),
    
    
constraint FK3 FOREIGN KEY (WHO_PERMITTED_LIB_ID) REFERENCES LIBRARIAN(LIB_ID),
constraint FK4 FOREIGN KEY (WHICH_BOOK_ID) REFERENCES BOOK(BOOK_ID),

PRIMARY KEY (WHICH_BOOK_ID , WHO_PERMITTED_LIB_ID)
);

/*FUTURE GUIDE ==========>>>>
Query practice from leetcode (database)
ERD Practice as many knowledge as you can
Procedure , function , trigger
need to make a website and add its data via mysql database
*/
